### ISSUE TITLE
Task not propery created by powershell script.

### ISSUE THREAD

**Issue by waryhermit** [dogi/ole--vagrant-vi#18]
The task is created OK, but it looks for the job/script information in `..\AppData\Local\Microsoft\Windows\PowerShell` which was not present. But when I deleted the task and created it again using the exact code given in the install script it did create the information in the proper location. I read that Register-ScheduledJob only creates it for the current user, perhaps the install script runs as a different user somehow?

A potential work around would be to make the icon point to a powershell script that starts vagrant and then loads the URL so it only starts vagrant when people actually want to use it. Then no task is needed.

**Comment by dogi** [comment]
@waryhermit think we install that script as admin user - Could that be the problem?

**Comment by waryhermit** [comment]
(hopefully) fixed by #22
