### ISSUE TITLE
Command Prompt(Admin) for Windows 8.1 Script

### ISSUE THREAD

**Issue by kylemathias** [dogi/ole--vagrant-vi#20]
OS: Windows 10 Pro

For the Command Prompt Script for Windows 8.1 and above, I had to run Command Prompt(Admin) in order for it to work. If i ran the script in the normal Command Prompt, my script would just stop at this position:

![image](https://cloud.githubusercontent.com/assets/26488295/24163825/e2b6de2c-0e28-11e7-9d72-ffaeade03a06.png)

Should i go ahead and make the changes? something like:

Note:
You might be required to run Command Prompt(Admin) for the line below to work properly.

**Comment by Loshi93** [comment]
@kylemathias I worked on Windows 8. You have to type the following command in the command prompt: @powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/dogi/ole--vagrant-vi/master/windows/install.ps1', 'install.ps1')" && @powershell -NoProfile -ExecutionPolicy Bypass -Command ".\install.ps1"

You don't need to run it on Command Prompt(admin). 
![image](https://cloud.githubusercontent.com/assets/24893117/24166089/67a5ac8e-0e2f-11e7-93fe-d8520fd29ee4.png)

**Comment by kylemathias** [comment]
That’s strange, I needed it to be in Command Prompt(admin) for it to work. Other Interns might have the same issue. Interns might have the script never install anything, then the intern might stop doing the internship before they ever really started. I know we want the instructions to be a concise as possible, but this small note might help retain more people. Just a thought.

**Comment by Loshi93** [comment]
@kylemathias In order to install BeLL App, first you have to enable virtualization in your OS. Enable Virtualization before installing BeLL. Can you please send me the screenshot of the error you got.

**Comment by kylemathias** [comment]
@Loshma93 I never got an error, it would just never proceed past that screen shot i sent.

**Comment by dogi** [comment]
thanks @kylemathias - if I understand you got it working by using an admin command prompt ... which is awesome
theoretically it should work already without admin rights ;)
wonder what on your system is different

@Loshma93 thanks virtualization is an other barrier to entry

**Comment by kylemathias** [comment]
Im going to close the issue, it seems that what happen to me was just an anomaly.
