### ISSUE TITLE
issues with take-home

### ISSUE THREAD

**Issue by Yurockkk** [dogi/ole--vagrant-vi#25]
I was not able to follow intructions of http://open-learning-exchange.github.io/#!pages/takehome.md in pairing the android app with community

After discussing with @dogi, we figured out that reason was this [change](https://github.com/dogi/ole--vagrant-vi/commit/0cc46491bb76778d1a5f6e35bc3c51365b6b194a)

He also told that we had changed this because vagrant update from version `1.9.3` to `1.9.4` had broken our `Vagrantfile` on Windows'es only

after changing it back it manually everything worked fine on my Mac ;)

**Comment by dogi** [comment]
@Yurockkk thanks

better fix would be to set version of vagrant install by `choco` back to version `1.9.3`
and switch to older `Vagrantfile` network configs ...

**Comment by dogi** [comment]
@Yurockkk thanks
